Dev kubra
NurKubra/rent-a-car pull request #5
Opened 2023-10-12 11:14 UTC by NurKubra

2023-10-12 11:34 UTC, eneskeskin4934 commented on src/main/java/com/rentacar/entity/abstracts/User.java
> +
@JsonIgnore
@ManyToMany
@JoinTable(name = "user_roles_table",
            joinColumns = @JoinColumn(name = "user_id"), //icinde bulundugumuz class
            inverseJoinColumns = @JoinColumn(name = "userRole_id")). //Karsi class

2023-10-12 11:42 UTC, eneskeskin4934 commented on src/main/java/com/rentacar/entity/concretes/user/UserRole.java
> +
@ManyToMany(mappedBy = "UserRoles", fetch = FetchType.LAZY)
private List<User> userList;

2023-10-12 11:45 UTC, eneskeskin4934 commented on src/main/java/com/rentacar/entity/abstracts/User.java
> +
<img width="679" alt="Bildschirmfoto 2023-10-12 um 13 25 52" src="https://github.com/NurKubra/rent-a-car/assets/45455532/2d9b52de-f6b0-450d-af0d-f51f8396f945">
<img width="682" alt="Bildschirmfoto 2023-10-12 um 13 30 33" src="https://github.com/NurKubra/rent-a-car/assets/45455532/aaeb1af9-e490-4fa4-b21a-38ed06174b48">

2023-10-12 11:45 UTC, eneskeskin4934 commented on src/main/java/com/rentacar/entity/abstracts/User.java
> +
Projede gecen manyToMany iliskilerinin ekran goruntusunu paylastim

2023-10-12 11:59 UTC, eneskeskin4934 commented on src/main/java/com/rentacar/entity/abstracts/User.java
> +    @Column(length = 50, nullable = false)
@Column(length = 50, nullable = false, unique = true)

2023-10-12 12:02 UTC, eneskeskin4934 commented on src/main/java/com/rentacar/entity/concretes/user/UserRole.java
> +@Builder  //toBuilder olmali mi ?
Bence toBuilder'a gerek yok hocam

2023-10-12 12:04 UTC, eneskeskin4934 commented on src/main/java/com/rentacar/entity/abstracts/User.java
> +    @Column(length = 120, nullable = false)
@JsonProperty(access = JsonProperty.Access.WRITE_ONLY) //hassas veri oldugu icin okuma islemlerinde kullanilmasin

2023-10-12 12:08 UTC, eneskeskin4934 commented on src/main/java/com/rentacar/entity/abstracts/User.java
Bunlar da eklenebilir
    @Column(unique = true)
    private String phoneNumber;

    @Enumerated(EnumType.STRING)
    private Gender gender;

2023-10-12 12:10 UTC, eneskeskin4934 requested changes
Hocam bir kac yere yorum yazdim

2023-10-12 12:12 UTC, eneskeskin4934 commented on src/main/java/com/rentacar/entity/abstracts/User.java
(length = 50, nullable = false, unique = true)

2023-10-12 12:16 UTC, eneskeskin4934 commented on src/main/java/com/rentacar/entity/abstracts/User.java
> +    @Column(length = 120, nullable = false)
@JsonProperty(access = JsonProperty.Access.WRITE_ONLY) //hassas veri oldugu icin okuma islemlerinde kullanilmasin

2023-10-12 12:17 UTC, eneskeskin4934 commented on src/main/java/com/rentacar/entity/abstracts/User.java
> +    @Column(length = 50, nullable = false)
@column(length = 50, nullable = false, unique = true) //unique eklenebilir

2023-10-12 12:18 UTC, eneskeskin4934 commented on src/main/java/com/rentacar/entity/concretes/user/UserRole.java
> +@Builder  //toBuilder olmali mi ?
Bence toBuilder'a gerek yok hocam

2023-10-12 22:02 UTC, NurKubra commented on src/main/java/com/rentacar/entity/abstracts/User.java
Hocam eklemistim aslinda ama gozukmuyor nedense :/

2023-10-12 22:03 UTC, NurKubra commented on src/main/java/com/rentacar/entity/abstracts/User.java
> +
dogru hocam duzeltiyorum hemen :)

2023-10-13 05:47 UTC, eneskeskin4934 approved these changes

2023-10-13 05:54 UTC, merged